name: s_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  shared_preferences: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  bot_toast: ^4.0.1
  cached_network_image: ^3.1.0
  optimized_cached_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  pull_to_refresh: ^2.0.0
  package_info: ^2.0.2
  url_launcher: ^6.0.6
  dio: ^4.0.0
  uni_links: ^0.5.1

  # -----------Need Native Config Start-------------
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  device_info: ^2.0.2
  flutter_app_badger: ^1.2.0
# -----------Need Native Config End-------------

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
